apiVersion: v1
kind: Namespace
metadata:
  name: tls-lab
  labels:
    name: tls-lab
    purpose: java-tls-ssl-practice
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    purpose: observability-stack
